"""Initial migration

Revision ID: a70d93fb2cde
Revises:
Create Date: 2026-06-02 10:05:37.826166

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'a70d93fb2cde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
